# Generated by Django 5.1.3 on 2024-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfAPP', '0002_productdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
